---
title: "HW2"
author: "Seungjin Kim, 2023277303"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1.
```{r, include = TRUE}
sqrt(2)
exp(5)
log10(20)
log(20)
gamma(5)
abs(-4.5)
round(pi, 2)
```
## Q2.
```{r, include = TRUE}
dnorm(5, mean = 5, sd = 1, log = FALSE)
dexp(1, rate = 5, log = FALSE)
dweibull(50, shape = 80, scale = 1.5, log = FALSE)
```
## Q3.
```{r, include = TRUE}
A <- 5
b <- 6
2*A+b^2
(A^5)*(3^b)
rm(list = ls())
```

## Q4.
```{r, include = TRUE}
Norm <- function(x, mu, sigma){
  value <- ((sigma*sqrt(2*pi))^(-1))*exp(-((x-mu)^2)/(2*(sigma^2)))
  return(10*value)
}
Norm(0, 0, 1)
```
## Q5.
```{r, include = TRUE}
sum(c(1:100)^2)
prod(c(1:10))
sum(cos(seq(pi/20, pi, by = pi/20)))
```
## Q6.
```{r, include = TRUE}
x <- seq(2, 18, by=2)
mat <- matrix(x, nrow = 3, ncol = 3, byrow = TRUE)
dimnames(mat)[[1]]<-c("A", "B", "C")
dimnames(mat)[[2]]<-c("가", "나", "다")
mat
mat[2, 3]
```

## Q7.
```{r, include = TRUE}
subset(iris, Species == "virginica")
```

## Q8.
```{r, include = TRUE}
c1 <- iris[,3]
c2 <- iris[,"Species"]
list1 <- list(c1, c2)
list1
```

## Q9.
```{r, include = TRUE}
Species_indexing <- function(data){
  for(i in 1:dim(data)[[1]]){
    if(data[i, "Species"] == "setosa"){print(1)}
    else if(data[i, "Species"] == "versicolor"){print(2)}
    else {print(3)}
  }  
}

Species_indexing(iris)
```